#!/bin/bash

./lastz  /home/mario/data/Pragya/sequences/pisi/pi7.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi8.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8.maff
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8.fa
./lastz  /home/mario/data/Pragya/sequences/pisi/piR2_10.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR3_11.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR4_12.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR2_14.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR7_13.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR3_15.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR6_16.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16.fa;
./lastz  /home/mario/data/Pragya/sequences/pisi/piR6_17.fa[multiple]  /home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16.fa --ambiguous=n  --ambiguous=iupac  --gfextend --chain --gapped  --identity=95 --continuity=95  --format=maf  --output=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16_piR6_17.maff;
java -jar  /home/mario/SINA.jar  showform=no  task=maf2fasta  srcdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16_piR6_17.maff  destdir=/home/mario/data/Pragya/sequences/pisi/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16_piR6_17.fa;

blastn   -db /home/mario/data/Pragya/sequences/syringae/blast_db/syringae  -query  /home/mario/data/Pragya/sequences/pisi/common_90/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16_piR6_17.fa   -outfmt '6 qseqid qstart qend sseqid sstart send length pident mismatch gapopen gaps score evalue' -num_threads 20 >  /home/mario/data/Pragya/common_90/pisi_syringae_blast.res
java -jar  /home/mario/SINA.jar  showform=no  task=querynotcovered  srcdir=/home/mario/data/Pragya/common_90/pisi_syringae_blast.res  destdir=/home/mario/data/Pragya/sequences/pisi/common_90/pi7_pi8_piR2_10_piR3_11_piR4_12_piR2_14_piR7_13_piR3_15_piR6_16_piR6_17.fa  file1=/home/mario/data/Pragya/pisi/common_90/pisi_specific.fa
blastn   -db /home/mario/data/Pragya/sequences/syringae/blast_db/syringae  -query  /home/mario/data/Pragya/common_90/pisi_specific.fa   -outfmt '6 qseqid qstart qend sseqid sstart send length pident mismatch gapopen gaps score evalue' -num_threads 20 >  /home/mario/data/Pragya/common_90/pisi_specific_syringae_blast.res
java -jar  /home/mario/SINA.jar  showform=no  task=querynotcovered  srcdir=/home/mario/data/Pragya/common_90/pisi_specific_syringae_blast.res  destdir=/home/mario/data/Pragya/common_90/pisi_specific.fa  file1=/home/mario/data/Pragya/common_90/pisi_more_specific.fa p1=70 p2=300
blastn   -db /home/mario/data/Pragya/sequences/outgroup/blast_db/outgroup  -query  /home/mario/data/Pragya/common_90/pisi_more_specific.fa   -outfmt '6 qseqid qstart qend sseqid sstart send length pident mismatch gapopen gaps score evalue' -num_threads 20 >  /home/mario/data/Pragya/common_90/pisi_more_specific_outgroup_blast.res
java -jar  /home/mario/SINA.jar  showform=no  task=querynotcovered  srcdir=/home/mario/data/Pragya/common_90/pisi_more_specific_outgroup_blast.res  destdir=/home/mario/data/Pragya/common_90/pisi_more_specific.fa  file1=/home/mario/data/Pragya/common_90/pisi_even_more_specific.fa p1=70 p2=300
blastn   -db /home/mario/data/Pragya/sequences/syringae/blast_db/syringae  -query  /home/mario/data/Pragya/common_90/pisi_even_more_specific.fa   -outfmt '6 qseqid qstart qend sseqid sstart send length pident mismatch gapopen gaps score evalue' -num_threads 20 >  /home/mario/data/Pragya/common_90/pisi_even_specific_syringae_blast.res

